from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from utils import text_utils

class Summarizer:
    '''
    A text summarization model wrapper.
    
    Attributes:
        model (AutoModelForSeq2SeqLM): Pretrained sequence-to-sequence model for summarization.
        tokenizer (AutoTokenizer): Tokenizer corresponding to the model.
    '''
    
    def __init__(self):
        '''
        Initialize summarization and tokenizer
        '''

        model_name = 'VietAI/vit5-base-vietnews-summarization'
        self._model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        self._tokenizer = AutoTokenizer.from_pretrained(model_name)             

    @property
    def model(self) -> AutoModelForSeq2SeqLM | None:
        '''
        Get the model
        '''

        if not self._model:
            return None
        
        return self._model

    @property
    def tokenizer(self) -> AutoTokenizer | None:
        '''
        Get the tokenizer for the model
        '''
        if not self._model:
            return None
        
        if not self._tokenizer:
            return None
        
        return self._tokenizer
    
    def _get_chunks_prgs(self, paragraph: str) -> list[str]:
        '''
        Chunking the input paragraph

        Args:
            paragraph (str): Input paragraph

        Returns:
            list[str]: List of text chunks
        '''
        
        chunks = text_utils.chunk_text(paragraph=paragraph)
        return chunks
    
    def _generate_summary_ids(self, paragraphs: list[str]):
        '''
        Generate token IDs representing summaries for a list of input paragraphs.

        Args:
            paragraphs (list[str]): Input paragraphs to be summarized

        Returns:
            torch.Tensor: Generated token IDs of the summaries.
        
        Notes:
            model_input['input_ids']: The tokenized representation of input paragraphs,
                                    shape=[batch_size, max_seq_len]
            multi_summary_id: The tokenized representation of summarized paragraphs,
                        shape=[batch_size, max_seq_len]
        '''

        model_input = self._tokenizer(
            paragraphs,
            return_tensors='pt',
            max_length=512,
            padding=True,
            truncation=True
        )
        
        multi_summary_ids = self._model.generate(
            model_input['input_ids'],
            max_length=200,      # summary result maximum lenth
            min_length=30,      # summary result minimum length
            length_penalty=1.0,
            num_beams=6,
            early_stopping=True
        )

        return multi_summary_ids
        
    def _decode_summary(self, multi_summary_ids) -> list[str]:
        '''
        Decode token IDs into human-readable summaries.

        Args:
            multi_summary_ids (torch.Tensor): Token IDs generated by the model.
        
        Returns:
            list[str]: List of decoded summary strings.
        '''
        
        return [self._tokenizer.decode(summary_ids, skip_special_tokens=True) for summary_ids in multi_summary_ids]

    def get_summary(self, paragraph: str) -> str:
        '''
        Chunking and summary the input paragraph
        
        Args:
            paragraph (str): Paragraph to be summary
            
        Returns:
            str: Summarization of the input paragraph'''
        
        chunks = self._get_chunks_prgs(paragraph=paragraph)
        multi_summary_ids = self._generate_summary_ids(paragraphs=chunks)
        summaries = self._decode_summary(multi_summary_ids=multi_summary_ids)
        return '\n'.join(summaries)