from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from utils import text_utils

class Summarizer:
    '''
    A text summarization model wrapper.
    
    Attributes:
        model (AutoModelForSeq2SeqLM): Pretrained sequence-to-sequence model for summarization.
        tokenizer (AutoTokenizer): Tokenizer corresponding to the model.
        summaries (list[str]): The summarized version of input paragraphs
    '''
    
    def __init__(self):
        '''
        Initialize the summarization model and tokenizer
        '''

        model_name = "VietAI/vit5-base-vietnews-summarization"
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

    def get_chunks_prgs(self, paragraph: str) -> list[str]:
        '''
        Chunking the input paragraph

        Args:
            paragraph (str): Input paragraph

        Returns:
            chunks (list[str]): List of text chunks
        '''
        
        chunks = text_utils.chunk_text(paragraph=paragraph)
        return chunks

    def generate_summary_ids(self, paragraphs: list[str]) -> list[str]:
        '''
        Generate token IDs representing summaries for a list of input paragraphs.

        Args:
            paragraphs (list[str]): Input paragraphs to be summarized

        Returns:
            summary_ids (torch.Tensor): Generated token IDs of the summaries.
        
        Notes:
            model_input['input_ids']: The tokenized representation of input paragraphs,
                                    shape=[batch_size, max_seq_len]
            summary_id: The tokenized representation of summarized paragraphs,
                        shape=[batch_size, max_seq_len]
        '''

        model_input = self.tokenizer(paragraphs,
                                return_tensors='pt',
                                max_length=512,
                                padding=True,
                                truncation=True)
        
        summary_ids = self.model.generate(
            model_input['input_ids'],
            max_length=200,      # Độ dài tối đa của summary
            min_length=50,      # Độ dài tối thiểu
            length_penalty=1.0,
            num_beams=6,
            early_stopping=True
        )

        return summary_ids
        
    def decode_summary(self, summary_ids) -> list[str]:
        '''
        Decode token IDs into human-readable summaries.

        Args:
            summary_ids (torch.Tensor): Token IDs generated by the model.
        
        Returns:
            list[str]: List of decoded summary strings.
        '''
        
        return [self.tokenizer.decode(ids, skip_special_tokens=True) for ids in summary_ids]

    def get_summaries(self, paragraph: str) -> list[str]:
        '''
        Summarize a list of paragraphs into shorter text

        Args:
            paragraphs (str): Input paragraphs to be summarized

        Returns:
            self.summaries (list[str]): List of text summaries
        '''
        chunks = self.get_chunks_prgs(paragraph=paragraph)
        summary_ids = self.generate_summary_ids(paragraphs=chunks)
        self.summaries = self.decode_summary(summary_ids=summary_ids)
        return self.summaries